apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  # TODO: Uncomment the following line to enable ingress
  # - ingress.yaml