apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
- ../../base

# NOTE: When applying production ingress, replace this with a patch
resources:
  - ingress.yaml

#patchesStrategicMerge:
#  - configmap.yaml
#  - ingress.yaml
