name: 'Python Tests Definition'
on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: string
      default_image_repo:
        description: 'Default repo'
        required: false
        type: string
        default: "us-docker.pkg.dev/jax-cs-registry/docker/geneweaver"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_REGISTRY_SA_KEY }}'
      - name: Docker Login
        run: gcloud auth configure-docker us-docker.pkg.dev,us-east1-docker.pkg.dev
      - name: Build
        run: |
          skaffold build \
          --default-repo=${{ inputs.default_image_repo }} \
          --file-output=build.json
      - name: Upload build artifact JSON
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: build.json
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_CLUSTER_SA_KEY }}'
      - name: Install Gcloud GKE Plugin
        run: sudo apt-get update && sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Get Cluster Credentials
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials ${{ vars.CLUSTER_NAME }} \
          --region ${{ vars.CLUSTER_REGION }} \
          --project ${{ vars.CLUSTER_PROJECT }}
      - name: Download coverage report artifact
        uses: actions/download-artifact@v3
        with:
          name: Build Artifacts
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Deploy
        run: |
          skaffold deploy \
          --profile ${{ inputs.environment }} \
          --build-artifacts=build.json
