name: 'Build & Deploy'
on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment profile'
        required: true
        type: string
      default_image_repo:
        description: 'Default repo'
        required: false
        type: string
        default: "us-docker.pkg.dev/jax-cs-registry/docker/geneweaver"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_REGISTRY_SA_KEY }}'
      - name: Docker Login
        run: gcloud auth configure-docker us-docker.pkg.dev,us-east1-docker.pkg.dev
      - name: Build
        run: |
          skaffold build \
          --default-repo=${{ inputs.default_image_repo }} \
          --file-output=build.json
      - name: Upload Build Artifact Information
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-json
          path: build.json
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Download Build Artifact Information
        uses: actions/download-artifact@v3
        with:
          name: build-artifact-json
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_CLUSTER_SA_KEY }}'
      - id: setup-gcloud
        name: Setup Gcloud
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: get-gke-credentials
        name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ vars.CLUSTER_NAME }}
          location: ${{ vars.CLUSTER_REGION }}
          project_id: ${{ vars.CLUSTER_PROJECT }}
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Deploy
        run: |
          skaffold deploy \
          --profile ${{ inputs.environment }} \
          --build-artifacts=build.json