name: Coverage
on:
  push:
    branches:
      - 'main'
jobs:
  check-coverage:
    uses: ./.github/workflows/_check-coverage-action.yml
    secrets: inherit
    permissions:
      pull-requests: write
    with:
      required-coverage: ${{ vars.REQUIRED_COVERAGE }}
      coverage-module: "geneweaver.api"
