name: Pull Request Test, Build and Deploy
on:
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']
    uses: ./.github/workflows/_run-tests-action.yml
    with:
      runner-os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      required-coverage: ${{ vars.REQUIRED_COVERAGE }}
  build_and_deploy:
    needs: test
    uses: ./.github/workflows/_skaffold-deploy-k8s.yaml
    with:
      cluster_project: ${{ vars.DEV_CLUSTER_PROJECT }}
      cluster_region: ${{ vars.CLUSTER_REGION }}
      cluster_name: ${{ vars.DEV_CLUSTER_NAME }}
      deployment_profile: ""${{ vars.DEV_CLUSTER_PROJECT }}--dev"
      default_image_repo: "us-east1-docker.pkg.dev/jax-cs-registry/docker-test/geneweaver"